### PR TITLE
Create ns for RTE on all platforms

### PR DESCRIPTION
**Pull request by Tal-or**
Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
now that we don't abuse the `openshift-monitoring` namespace anymore, this seems the right fix.

**Comment by Tal-or** [comment]
I'm not fully aware if there is a historical reason for creating Namespace only under K8S, but definitely when using the deployer directly (not via numaresource-operator) the ns is needed.

**Comment by fromanirh** [comment]
> I'm not fully aware if there is a historical reason for creating Namespace only under K8S, but definitely when using the deployer directly (not via numaresource-operator) the ns is needed.

Initially, I was piggybacking on `openshift-monitoring` namespace and on the `node-exporter` SCC to save time and to have a good-enough(ish) solution. Nowadays, thanks to the work of @cynepco3hahue , RTE goes cleanly with its own SCC, namespace and everything else.

**Pull request merged**
